### ISSUE TITLE
java.lang.ClassNotFoundException: com.avaje.ebeaninternal.api.SpiQuery PluginClassLoader[org.avaje.ebean.typequery.enhancer, 1.2.1] Information:	at org.avaje.ebean.typequery.agent.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1684)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm-typequery-agent#2]
Information:Ebean type query enhancement started with packages:[org.example.domain.query]
Information:java.lang.RuntimeException: java.lang.ClassNotFoundException: com.avaje.ebeaninternal.api.SpiQuery PluginClassLoader[org.avaje.ebean.typequery.enhancer, 1.2.1]
Information:	at org.avaje.ebean.typequery.agent.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1684)
Information:	at org.avaje.ebean.typequery.agent.asm.ClassWriter.getMergedType(ClassWriter.java:1654)
Information:	at org.avaje.ebean.typequery.agent.asm.Frame.merge(Frame.java:1426)
Information:	at org.avaje.ebean.typequery.agent.asm.Frame.merge(Frame.java:1331)
Information:	at org.avaje.ebean.typequery.agent.asm.MethodWriter.visitMaxs(MethodWriter.java:1475)
Information:	at org.avaje.ebean.typequery.agent.asm.MethodVisitor.visitMaxs(MethodVisitor.java:867)
Information:	at org.avaje.ebean.typequery.agent.asm.ClassReader.readCode(ClassReader.java:1567)
Information:	at org.avaje.ebean.typequery.agent.asm.ClassReader.readMethod(ClassReader.java:1017)
Information:	at org.avaje.ebean.typequery.agent.asm.ClassReader.accept(ClassReader.java:693)
Information:	at org.avaje.ebean.typequery.agent.asm.ClassReader.accept(ClassReader.java:506)
Information:	at org.avaje.ebean.typequery.agent.Transformer.enhancement(Transformer.java:104)
Information:	at org.avaje.ebean.typequery.agent.Transformer.transform(Transformer.java:78)
Information:	at org.avaje.idea.typequery.plugin.InputStreamTransform.transform(InputStreamTransform.java:48)
Information:	at org.avaje.idea.typequery.plugin.InputStreamTransform.transform(InputStreamTransform.java:34)
Information:	at org.avaje.idea.typequery.plugin.TypeQueryEnhancementTask.doProcess(TypeQueryEnhancementTask.java:115)
Information:	at org.avaje.idea.typequery.plugin.TypeQueryEnhancementTask.access$000(TypeQueryEnhancementTask.java:30)
Information:	at org.avaje.idea.typequery.plugin.TypeQueryEnhancementTask$1.run(TypeQueryEnhancementTask.java:49)
Information:	at com.intellij.util.ActionRunner$1.run(ActionRunner.java:31)

**Comment by rbygrave** [comment]
What this issue means is that we need to use a ClassWriter that is aware of the external classLoader.
